### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by AbedHadri** [daidorian09/Generic-Couchbase-Repository#2]
https://github.com/daidorian09/Generic-Couchbase-Repository/blob/89cf970b0d7a086e300e180a2204f425a661cbc1/src/main/java/com/trendyol/cbcrudpoc/repository/cocuhbase/AbstractCouchbaseRepository.java#L81

Collections.<type_here>emptyList();

**Comment by daidorian09** [comment]
Good catch for readability 👍
